--------------------------------------------------------------------------------
-- PROYECTO   : PulsoCare - Monitoreo de signos vitales en hospitalizacion
--              domiciliaria / clinica
-- ASIGNATURA : Taller Aplicado de Software (TSY2201) - DUOC UC
-- EQUIPO     : Grupo 5 - Daniel San Juan / Diego Munoz
-- ENTREGA    : Semana 4 - Modelo de datos (base de datos relacional normalizada)
-- MOTOR      : Oracle Autonomous Database (compatible 19c / 21c / 23ai)
-- DESCRIPCION: Script DDL con la estructura final de la base de datos, en
--              Tercera Forma Normal (3FN), incluyendo claves primarias,
--              foraneas, restricciones de integridad, indices y datos de
--              catalogo (seeds) necesarios para operar la plataforma.
--------------------------------------------------------------------------------
-- NOTA SOBRE LOS SIGNOS VITALES:
--   Cada lectura de signo vital se almacena en PC_LECTURA_SIGNO_VITAL con:
--     * la marca de tiempo de la medicion (FECHA_MEDICION),
--     * el tipo de signo vital y su unidad  (FK -> PC_SIGNO_VITAL: bpm, %, mmHg, C, rpm),
--     * el paciente dueno de la lectura      (FK -> PC_PACIENTE, vinculado al subject_id de MIMIC),
--     * el valor medido                      (VALOR_NUM).
--------------------------------------------------------------------------------

--==============================================================================
-- (OPCIONAL) LIMPIEZA: ejecutar solo si se desea recrear el modelo desde cero.
-- Quitar el comentario de bloque para activar. El orden respeta las dependencias.
--==============================================================================
/*
DROP TABLE PC_BITACORA_ACCESO        CASCADE CONSTRAINTS;
DROP TABLE PC_TOKEN_RECUPERACION     CASCADE CONSTRAINTS;
DROP TABLE PC_NOTIFICACION           CASCADE CONSTRAINTS;
DROP TABLE PC_ALERTA                 CASCADE CONSTRAINTS;
DROP TABLE PC_LECTURA_SIGNO_VITAL    CASCADE CONSTRAINTS;
DROP TABLE PC_UMBRAL                 CASCADE CONSTRAINTS;
DROP TABLE PC_ASIGNACION_CUIDADO     CASCADE CONSTRAINTS;
DROP TABLE PC_EPISODIO_CLINICO       CASCADE CONSTRAINTS;
DROP TABLE PC_PACIENTE_DIAGNOSTICO   CASCADE CONSTRAINTS;
DROP TABLE PC_PACIENTE               CASCADE CONSTRAINTS;
DROP TABLE PC_ROL_PERMISO            CASCADE CONSTRAINTS;
DROP TABLE PC_USUARIO                CASCADE CONSTRAINTS;
DROP TABLE PC_PERMISO                CASCADE CONSTRAINTS;
DROP TABLE PC_ROL                    CASCADE CONSTRAINTS;
DROP TABLE PC_PARENTESCO             CASCADE CONSTRAINTS;
DROP TABLE PC_COMUNA                 CASCADE CONSTRAINTS;
DROP TABLE PC_MODALIDAD_ATENCION     CASCADE CONSTRAINTS;
DROP TABLE PC_DIAGNOSTICO            CASCADE CONSTRAINTS;
DROP TABLE PC_SIGNO_VITAL            CASCADE CONSTRAINTS;
DROP TABLE PC_ESTADO_PACIENTE        CASCADE CONSTRAINTS;
DROP TABLE PC_ESTADO_LECTURA         CASCADE CONSTRAINTS;
DROP TABLE PC_NIVEL_ALERTA           CASCADE CONSTRAINTS;
DROP TABLE PC_ESTADO_ALERTA          CASCADE CONSTRAINTS;
DROP TABLE PC_ESTADO_NOTIFICACION    CASCADE CONSTRAINTS;
*/

--==============================================================================
-- 1. TABLAS DE CATALOGO (datos de referencia)
--==============================================================================

------------------------------------------------------------------- ROL
CREATE TABLE PC_ROL (
    ID_ROL        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO        VARCHAR2(20)  NOT NULL,
    NOMBRE        VARCHAR2(50)  NOT NULL,
    DESCRIPCION   VARCHAR2(200),
    CONSTRAINT PK_ROL        PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROL_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- PERMISO
CREATE TABLE PC_PERMISO (
    ID_PERMISO    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO        VARCHAR2(20)  NOT NULL,   -- VER / EDITAR / COMPLETO
    NOMBRE        VARCHAR2(50)  NOT NULL,
    DESCRIPCION   VARCHAR2(200),
    CONSTRAINT PK_PERMISO        PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UQ_PERMISO_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- PARENTESCO
CREATE TABLE PC_PARENTESCO (
    ID_PARENTESCO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE        VARCHAR2(50)  NOT NULL,   -- Hijo/a, Conyuge, Hermano/a, etc.
    CONSTRAINT PK_PARENTESCO        PRIMARY KEY (ID_PARENTESCO),
    CONSTRAINT UQ_PARENTESCO_NOMBRE UNIQUE (NOMBRE)
);

------------------------------------------------------------------- COMUNA
CREATE TABLE PC_COMUNA (
    ID_COMUNA     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE        VARCHAR2(80)  NOT NULL,
    REGION        VARCHAR2(80),
    CONSTRAINT PK_COMUNA        PRIMARY KEY (ID_COMUNA),
    CONSTRAINT UQ_COMUNA_NOMBRE UNIQUE (NOMBRE)
);

------------------------------------------------------------------- MODALIDAD_ATENCION
CREATE TABLE PC_MODALIDAD_ATENCION (
    ID_MODALIDAD  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE        VARCHAR2(50)  NOT NULL,   -- Domicilio, Clinica, Hosp. Domiciliaria
    CONSTRAINT PK_MODALIDAD        PRIMARY KEY (ID_MODALIDAD),
    CONSTRAINT UQ_MODALIDAD_NOMBRE UNIQUE (NOMBRE)
);

------------------------------------------------------------------- DIAGNOSTICO
CREATE TABLE PC_DIAGNOSTICO (
    ID_DIAGNOSTICO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO_ICD     VARCHAR2(15),            -- referencia opcional CIE-10
    NOMBRE         VARCHAR2(200) NOT NULL,  -- ej: Insuficiencia cardiaca congestiva
    CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (ID_DIAGNOSTICO)
);

------------------------------------------------------------------- SIGNO_VITAL (tipo + unidad)
CREATE TABLE PC_SIGNO_VITAL (
    ID_SIGNO_VITAL  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO          VARCHAR2(15)  NOT NULL, -- FC, SPO2, PAS, PAD, TEMP, FR
    NOMBRE          VARCHAR2(60)  NOT NULL, -- Frecuencia cardiaca, etc.
    UNIDAD          VARCHAR2(15)  NOT NULL, -- bpm, %, mmHg, C, rpm
    ITEMID_MIMIC    NUMBER,                 -- itemid de origen en MIMIC (d_items)
    RANGO_MIN       NUMBER(6,2),            -- limite normal inferior por defecto
    RANGO_MAX       NUMBER(6,2),            -- limite normal superior por defecto
    DECIMALES       NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SIGNO_VITAL        PRIMARY KEY (ID_SIGNO_VITAL),
    CONSTRAINT UQ_SIGNO_VITAL_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_SIGNO_VITAL_RANGO  CHECK (RANGO_MIN IS NULL OR RANGO_MAX IS NULL OR RANGO_MIN <= RANGO_MAX)
);

------------------------------------------------------------------- ESTADO_PACIENTE
CREATE TABLE PC_ESTADO_PACIENTE (
    ID_ESTADO_PACIENTE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO             VARCHAR2(20) NOT NULL,  -- ESTABLE, OBSERVACION, CRITICO, ALTA
    NOMBRE             VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ESTADO_PACIENTE        PRIMARY KEY (ID_ESTADO_PACIENTE),
    CONSTRAINT UQ_ESTADO_PACIENTE_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- ESTADO_LECTURA
CREATE TABLE PC_ESTADO_LECTURA (
    ID_ESTADO_LECTURA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO            VARCHAR2(20) NOT NULL,   -- NORMAL, ATENCION, CRITICO
    NOMBRE            VARCHAR2(50) NOT NULL,
    COLOR             VARCHAR2(20),            -- verde, amarillo, rojo
    CONSTRAINT PK_ESTADO_LECTURA        PRIMARY KEY (ID_ESTADO_LECTURA),
    CONSTRAINT UQ_ESTADO_LECTURA_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- NIVEL_ALERTA
CREATE TABLE PC_NIVEL_ALERTA (
    ID_NIVEL_ALERTA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO          VARCHAR2(20) NOT NULL,     -- AMARILLO, ROJO
    NOMBRE          VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_NIVEL_ALERTA        PRIMARY KEY (ID_NIVEL_ALERTA),
    CONSTRAINT UQ_NIVEL_ALERTA_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- ESTADO_ALERTA
CREATE TABLE PC_ESTADO_ALERTA (
    ID_ESTADO_ALERTA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO           VARCHAR2(20) NOT NULL,    -- GENERADA, NOTIFICADA, RECONOCIDA, RESUELTA
    NOMBRE           VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ESTADO_ALERTA        PRIMARY KEY (ID_ESTADO_ALERTA),
    CONSTRAINT UQ_ESTADO_ALERTA_CODIGO UNIQUE (CODIGO)
);

------------------------------------------------------------------- ESTADO_NOTIFICACION
CREATE TABLE PC_ESTADO_NOTIFICACION (
    ID_ESTADO_NOTIFICACION NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CODIGO                 VARCHAR2(20) NOT NULL, -- PENDIENTE, ENVIADO, ENTREGADO, FALLIDO
    NOMBRE                 VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ESTADO_NOTIFICACION        PRIMARY KEY (ID_ESTADO_NOTIFICACION),
    CONSTRAINT UQ_ESTADO_NOTIFICACION_CODIGO UNIQUE (CODIGO)
);

--==============================================================================
-- 2. SEGURIDAD Y USUARIOS (RBAC)
--==============================================================================

------------------------------------------------------------------- ROL_PERMISO (N:M)
CREATE TABLE PC_ROL_PERMISO (
    ID_ROL        NUMBER NOT NULL,
    ID_PERMISO    NUMBER NOT NULL,
    CONSTRAINT PK_ROL_PERMISO       PRIMARY KEY (ID_ROL, ID_PERMISO),
    CONSTRAINT FK_ROLPERM_ROL       FOREIGN KEY (ID_ROL)     REFERENCES PC_ROL (ID_ROL),
    CONSTRAINT FK_ROLPERM_PERMISO   FOREIGN KEY (ID_PERMISO) REFERENCES PC_PERMISO (ID_PERMISO)
);

------------------------------------------------------------------- USUARIO
-- Usuarios de la plataforma: medico, enfermero, familiar y administrador.
-- La autenticacion se federa con Azure Entra ID (IDaaS); se guarda el
-- identificador externo (ENTRA_OID). HASH_CONTRASENA queda como respaldo local
-- opcional (ej. contrasena temporal creada por el administrador).
CREATE TABLE PC_USUARIO (
    ID_USUARIO        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ROL            NUMBER        NOT NULL,
    ID_PARENTESCO     NUMBER,                       -- solo aplica a familiares
    NOMBRE            VARCHAR2(60)  NOT NULL,
    APELLIDO_PATERNO  VARCHAR2(60)  NOT NULL,
    APELLIDO_MATERNO  VARCHAR2(60),
    FECHA_NACIMIENTO  DATE,
    CORREO            VARCHAR2(120) NOT NULL,        -- correo institucional @pulsocare.cl
    TELEFONO          VARCHAR2(20),                  -- destino de notificaciones SMS
    ENTRA_OID         VARCHAR2(100),                 -- Object ID en Azure Entra ID
    HASH_CONTRASENA   VARCHAR2(255),                 -- respaldo local / clave temporal
    ESTADO            VARCHAR2(15)  DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ID_CREADO_POR     NUMBER,                        -- administrador que lo creo
    CONSTRAINT PK_USUARIO        PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO')),
    CONSTRAINT FK_USUARIO_ROL        FOREIGN KEY (ID_ROL)        REFERENCES PC_ROL (ID_ROL),
    CONSTRAINT FK_USUARIO_PARENTESCO FOREIGN KEY (ID_PARENTESCO) REFERENCES PC_PARENTESCO (ID_PARENTESCO),
    CONSTRAINT FK_USUARIO_CREADOPOR  FOREIGN KEY (ID_CREADO_POR) REFERENCES PC_USUARIO (ID_USUARIO)
);

------------------------------------------------------------------- TOKEN_RECUPERACION
-- Soporta la pantalla "Recupera tu contrasena".
CREATE TABLE PC_TOKEN_RECUPERACION (
    ID_TOKEN          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_USUARIO        NUMBER        NOT NULL,
    TOKEN_HASH        VARCHAR2(255) NOT NULL,
    FECHA_CREACION    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION  TIMESTAMP     NOT NULL,
    USADO             NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TOKEN_RECUPERACION PRIMARY KEY (ID_TOKEN),
    CONSTRAINT CK_TOKEN_USADO        CHECK (USADO IN (0,1)),
    CONSTRAINT FK_TOKEN_USUARIO      FOREIGN KEY (ID_USUARIO) REFERENCES PC_USUARIO (ID_USUARIO)
);

--==============================================================================
-- 3. PACIENTES Y CONTEXTO CLINICO
--==============================================================================

------------------------------------------------------------------- PACIENTE
-- SUBJECT_ID vincula al paciente con su origen en el dataset MIMIC-IV.
CREATE TABLE PC_PACIENTE (
    ID_PACIENTE        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    SUBJECT_ID         NUMBER        NOT NULL,        -- identificador MIMIC-IV
    NOMBRE             VARCHAR2(60)  NOT NULL,
    APELLIDO_PATERNO   VARCHAR2(60)  NOT NULL,
    APELLIDO_MATERNO   VARCHAR2(60),
    FECHA_NACIMIENTO   DATE,
    SEXO               CHAR(1),                        -- M / F / O
    ID_COMUNA          NUMBER,
    ID_MODALIDAD       NUMBER,
    ID_ESTADO_PACIENTE NUMBER,
    FECHA_ALTA_SISTEMA TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PACIENTE        PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT UQ_PACIENTE_SUBJECT UNIQUE (SUBJECT_ID),
    CONSTRAINT CK_PACIENTE_SEXO   CHECK (SEXO IN ('M','F','O')),
    CONSTRAINT FK_PACIENTE_COMUNA    FOREIGN KEY (ID_COMUNA)          REFERENCES PC_COMUNA (ID_COMUNA),
    CONSTRAINT FK_PACIENTE_MODALIDAD FOREIGN KEY (ID_MODALIDAD)       REFERENCES PC_MODALIDAD_ATENCION (ID_MODALIDAD),
    CONSTRAINT FK_PACIENTE_ESTADO    FOREIGN KEY (ID_ESTADO_PACIENTE) REFERENCES PC_ESTADO_PACIENTE (ID_ESTADO_PACIENTE)
);

------------------------------------------------------------------- PACIENTE_DIAGNOSTICO (N:M)
CREATE TABLE PC_PACIENTE_DIAGNOSTICO (
    ID_PACIENTE     NUMBER      NOT NULL,
    ID_DIAGNOSTICO  NUMBER      NOT NULL,
    ES_PRINCIPAL    NUMBER(1)   DEFAULT 0 NOT NULL,
    FECHA_REGISTRO  DATE        DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PAC_DIAG       PRIMARY KEY (ID_PACIENTE, ID_DIAGNOSTICO),
    CONSTRAINT CK_PAC_DIAG_PRINC CHECK (ES_PRINCIPAL IN (0,1)),
    CONSTRAINT FK_PACDIAG_PAC    FOREIGN KEY (ID_PACIENTE)    REFERENCES PC_PACIENTE (ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_PACDIAG_DIAG   FOREIGN KEY (ID_DIAGNOSTICO) REFERENCES PC_DIAGNOSTICO (ID_DIAGNOSTICO)
);

------------------------------------------------------------------- EPISODIO_CLINICO
-- Periodo de atencion/monitoreo del paciente (mapea admission/icustay de MIMIC).
CREATE TABLE PC_EPISODIO_CLINICO (
    ID_EPISODIO      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PACIENTE      NUMBER       NOT NULL,
    HADM_ID          NUMBER,                      -- ingreso hospitalario MIMIC
    STAY_ID          NUMBER,                      -- estancia MIMIC
    ID_MODALIDAD     NUMBER,
    UNIDAD           VARCHAR2(80),                -- unidad/servicio de atencion
    FECHA_INGRESO    TIMESTAMP    NOT NULL,
    FECHA_EGRESO     TIMESTAMP,
    ACTIVO           NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT PK_EPISODIO       PRIMARY KEY (ID_EPISODIO),
    CONSTRAINT CK_EPISODIO_ACT   CHECK (ACTIVO IN (0,1)),
    CONSTRAINT CK_EPISODIO_FECHA CHECK (FECHA_EGRESO IS NULL OR FECHA_EGRESO >= FECHA_INGRESO),
    CONSTRAINT FK_EPISODIO_PAC       FOREIGN KEY (ID_PACIENTE)  REFERENCES PC_PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_EPISODIO_MODALIDAD FOREIGN KEY (ID_MODALIDAD) REFERENCES PC_MODALIDAD_ATENCION (ID_MODALIDAD)
);

------------------------------------------------------------------- ASIGNACION_CUIDADO (N:M usuario-paciente)
-- Define el equipo de cuidado: que medico/enfermero/familiar accede a que
-- paciente. Es la base del control de acceso por paciente.
CREATE TABLE PC_ASIGNACION_CUIDADO (
    ID_ASIGNACION   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_USUARIO      NUMBER      NOT NULL,
    ID_PACIENTE     NUMBER      NOT NULL,
    FECHA_INICIO    DATE        DEFAULT SYSDATE NOT NULL,
    FECHA_FIN       DATE,
    ACTIVO          NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ASIGNACION      PRIMARY KEY (ID_ASIGNACION),
    CONSTRAINT UQ_ASIGNACION      UNIQUE (ID_USUARIO, ID_PACIENTE, FECHA_INICIO),
    CONSTRAINT CK_ASIGNACION_ACT  CHECK (ACTIVO IN (0,1)),
    CONSTRAINT FK_ASIGN_USUARIO   FOREIGN KEY (ID_USUARIO)  REFERENCES PC_USUARIO (ID_USUARIO),
    CONSTRAINT FK_ASIGN_PACIENTE  FOREIGN KEY (ID_PACIENTE) REFERENCES PC_PACIENTE (ID_PACIENTE)
);

--==============================================================================
-- 4. UMBRALES, LECTURAS, ALERTAS Y NOTIFICACIONES (nucleo en tiempo real)
--==============================================================================

------------------------------------------------------------------- UMBRAL
-- Limites personalizados por paciente y signo vital. Es el dato que la
-- aplicacion cachea en ElastiCache para evaluar cada lectura en tiempo real.
CREATE TABLE PC_UMBRAL (
    ID_UMBRAL          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PACIENTE        NUMBER       NOT NULL,
    ID_SIGNO_VITAL     NUMBER       NOT NULL,
    VALOR_MIN          NUMBER(6,2),              -- limite normal inferior
    VALOR_MAX          NUMBER(6,2),              -- limite normal superior
    VALOR_MIN_CRITICO  NUMBER(6,2),              -- umbral de alerta roja inferior
    VALOR_MAX_CRITICO  NUMBER(6,2),              -- umbral de alerta roja superior
    VIGENTE            NUMBER(1)    DEFAULT 1 NOT NULL,
    VIGENTE_DESDE      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    ID_DEFINIDO_POR    NUMBER,                   -- medico que ajusto el umbral
    CONSTRAINT PK_UMBRAL          PRIMARY KEY (ID_UMBRAL),
    CONSTRAINT CK_UMBRAL_VIGENTE  CHECK (VIGENTE IN (0,1)),
    CONSTRAINT CK_UMBRAL_RANGO    CHECK (VALOR_MIN IS NULL OR VALOR_MAX IS NULL OR VALOR_MIN <= VALOR_MAX),
    CONSTRAINT FK_UMBRAL_PAC      FOREIGN KEY (ID_PACIENTE)     REFERENCES PC_PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_UMBRAL_SIGNO    FOREIGN KEY (ID_SIGNO_VITAL)  REFERENCES PC_SIGNO_VITAL (ID_SIGNO_VITAL),
    CONSTRAINT FK_UMBRAL_DEFPOR   FOREIGN KEY (ID_DEFINIDO_POR) REFERENCES PC_USUARIO (ID_USUARIO)
);

------------------------------------------------------------------- LECTURA_SIGNO_VITAL (serie de tiempo)
-- Una fila por medicion. Es la tabla de mayor volumen del sistema.
-- SUGERENCIA (no obligatoria): en produccion conviene particionar por RANGE
-- mensual sobre FECHA_MEDICION para gestionar el historico. Se deja como tabla
-- estandar con indice compuesto para que el script sea directamente ejecutable.
CREATE TABLE PC_LECTURA_SIGNO_VITAL (
    ID_LECTURA        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PACIENTE       NUMBER        NOT NULL,
    ID_EPISODIO       NUMBER,
    ID_SIGNO_VITAL    NUMBER        NOT NULL,
    VALOR_NUM         NUMBER(8,2),                 -- valor numerico medido
    VALOR_TEXTO       VARCHAR2(60),                -- valores no numericos (opcional)
    UNIDAD            VARCHAR2(15),                -- unidad al momento de medir
    FECHA_MEDICION    TIMESTAMP     NOT NULL,      -- marca de tiempo de la medicion
    FECHA_REGISTRO    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL, -- ingesta en plataforma
    ID_ESTADO_LECTURA NUMBER,
    ORIGEN            VARCHAR2(30)  DEFAULT 'MIMIC_SIM' NOT NULL,
    CONSTRAINT PK_LECTURA       PRIMARY KEY (ID_LECTURA),
    CONSTRAINT FK_LECTURA_PAC      FOREIGN KEY (ID_PACIENTE)       REFERENCES PC_PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_LECTURA_EPISODIO FOREIGN KEY (ID_EPISODIO)       REFERENCES PC_EPISODIO_CLINICO (ID_EPISODIO),
    CONSTRAINT FK_LECTURA_SIGNO    FOREIGN KEY (ID_SIGNO_VITAL)    REFERENCES PC_SIGNO_VITAL (ID_SIGNO_VITAL),
    CONSTRAINT FK_LECTURA_ESTADO   FOREIGN KEY (ID_ESTADO_LECTURA) REFERENCES PC_ESTADO_LECTURA (ID_ESTADO_LECTURA)
);

------------------------------------------------------------------- ALERTA
-- Evento generado cuando una lectura supera los umbrales del paciente.
CREATE TABLE PC_ALERTA (
    ID_ALERTA         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_LECTURA        NUMBER        NOT NULL,      -- lectura que la disparo
    ID_PACIENTE       NUMBER        NOT NULL,
    ID_SIGNO_VITAL    NUMBER        NOT NULL,
    ID_NIVEL_ALERTA   NUMBER        NOT NULL,      -- amarillo / rojo
    ID_ESTADO_ALERTA  NUMBER        NOT NULL,      -- generada / notificada / etc.
    VALOR_REGISTRADO  NUMBER(8,2),
    UMBRAL_VIOLADO    VARCHAR2(10),                -- MIN / MAX
    FECHA_GENERACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ID_RECONOCIDA_POR NUMBER,                      -- usuario que reconoce la alerta
    FECHA_RECONOCIM   TIMESTAMP,
    CONSTRAINT PK_ALERTA        PRIMARY KEY (ID_ALERTA),
    CONSTRAINT CK_ALERTA_UMBRAL CHECK (UMBRAL_VIOLADO IS NULL OR UMBRAL_VIOLADO IN ('MIN','MAX')),
    CONSTRAINT FK_ALERTA_LECTURA  FOREIGN KEY (ID_LECTURA)        REFERENCES PC_LECTURA_SIGNO_VITAL (ID_LECTURA),
    CONSTRAINT FK_ALERTA_PAC      FOREIGN KEY (ID_PACIENTE)       REFERENCES PC_PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_ALERTA_SIGNO    FOREIGN KEY (ID_SIGNO_VITAL)    REFERENCES PC_SIGNO_VITAL (ID_SIGNO_VITAL),
    CONSTRAINT FK_ALERTA_NIVEL    FOREIGN KEY (ID_NIVEL_ALERTA)   REFERENCES PC_NIVEL_ALERTA (ID_NIVEL_ALERTA),
    CONSTRAINT FK_ALERTA_ESTADO   FOREIGN KEY (ID_ESTADO_ALERTA)  REFERENCES PC_ESTADO_ALERTA (ID_ESTADO_ALERTA),
    CONSTRAINT FK_ALERTA_RECONPOR FOREIGN KEY (ID_RECONOCIDA_POR) REFERENCES PC_USUARIO (ID_USUARIO)
);

------------------------------------------------------------------- NOTIFICACION (SMS)
-- Registro del envio de SMS (AWS End User Messaging) a un destinatario.
CREATE TABLE PC_NOTIFICACION (
    ID_NOTIFICACION        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ALERTA              NUMBER        NOT NULL,
    ID_USUARIO_DESTINO     NUMBER        NOT NULL,
    ID_ESTADO_NOTIFICACION NUMBER        NOT NULL,
    CANAL                  VARCHAR2(15)  DEFAULT 'SMS' NOT NULL,
    TELEFONO_DESTINO       VARCHAR2(20),
    MENSAJE                VARCHAR2(480),
    ID_PROVEEDOR_MSG       VARCHAR2(100),          -- message id del proveedor
    INTENTOS               NUMBER(2)     DEFAULT 0 NOT NULL,
    FECHA_ENVIO            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ENTREGA          TIMESTAMP,
    CONSTRAINT PK_NOTIFICACION      PRIMARY KEY (ID_NOTIFICACION),
    CONSTRAINT FK_NOTIF_ALERTA      FOREIGN KEY (ID_ALERTA)              REFERENCES PC_ALERTA (ID_ALERTA),
    CONSTRAINT FK_NOTIF_USUARIO     FOREIGN KEY (ID_USUARIO_DESTINO)     REFERENCES PC_USUARIO (ID_USUARIO),
    CONSTRAINT FK_NOTIF_ESTADO      FOREIGN KEY (ID_ESTADO_NOTIFICACION) REFERENCES PC_ESTADO_NOTIFICACION (ID_ESTADO_NOTIFICACION)
);

--==============================================================================
-- 5. AUDITORIA (trazabilidad de accesos a datos clinicos)
--==============================================================================

------------------------------------------------------------------- BITACORA_ACCESO
CREATE TABLE PC_BITACORA_ACCESO (
    ID_BITACORA     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_USUARIO      NUMBER        NOT NULL,
    ID_PACIENTE     NUMBER,
    ACCION          VARCHAR2(50)  NOT NULL,        -- LOGIN, VER_PACIENTE, EDITAR_UMBRAL...
    DETALLE         VARCHAR2(400),
    DIRECCION_IP    VARCHAR2(45),
    FECHA_EVENTO    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BITACORA      PRIMARY KEY (ID_BITACORA),
    CONSTRAINT FK_BITACORA_USR  FOREIGN KEY (ID_USUARIO)  REFERENCES PC_USUARIO (ID_USUARIO),
    CONSTRAINT FK_BITACORA_PAC  FOREIGN KEY (ID_PACIENTE) REFERENCES PC_PACIENTE (ID_PACIENTE)
);

--==============================================================================
-- 6. INDICES (rendimiento de consultas frecuentes)
--==============================================================================
-- Historico de un paciente por signo vital ordenado por tiempo (grafica/tabla).
CREATE INDEX IX_LECTURA_PAC_SIGNO_FEC ON PC_LECTURA_SIGNO_VITAL (ID_PACIENTE, ID_SIGNO_VITAL, FECHA_MEDICION);
CREATE INDEX IX_LECTURA_EPISODIO      ON PC_LECTURA_SIGNO_VITAL (ID_EPISODIO);
-- Bandeja de alertas por paciente / estado.
CREATE INDEX IX_ALERTA_PAC_FECHA      ON PC_ALERTA (ID_PACIENTE, FECHA_GENERACION);
CREATE INDEX IX_ALERTA_ESTADO         ON PC_ALERTA (ID_ESTADO_ALERTA);
-- Notificaciones por alerta y por estado de envio.
CREATE INDEX IX_NOTIF_ALERTA          ON PC_NOTIFICACION (ID_ALERTA);
CREATE INDEX IX_NOTIF_ESTADO          ON PC_NOTIFICACION (ID_ESTADO_NOTIFICACION);
-- Acceso a equipos de cuidado.
CREATE INDEX IX_ASIGNACION_PAC        ON PC_ASIGNACION_CUIDADO (ID_PACIENTE);
CREATE INDEX IX_ASIGNACION_USR        ON PC_ASIGNACION_CUIDADO (ID_USUARIO);
-- Umbrales vigentes por paciente.
CREATE INDEX IX_UMBRAL_PAC_SIGNO      ON PC_UMBRAL (ID_PACIENTE, ID_SIGNO_VITAL);

--==============================================================================
-- 7. DATOS DE CATALOGO (SEEDS)
--==============================================================================

-- Roles
INSERT INTO PC_ROL (CODIGO, NOMBRE, DESCRIPCION) VALUES ('MEDICO',  'Medico',        'Profesional a cargo del paciente; configura umbrales y ve historico completo');
INSERT INTO PC_ROL (CODIGO, NOMBRE, DESCRIPCION) VALUES ('ENFERMERO','Enfermero',    'Personal de enfermeria que monitorea y registra evolucion');
INSERT INTO PC_ROL (CODIGO, NOMBRE, DESCRIPCION) VALUES ('FAMILIAR','Familiar',      'Familiar designado; visualiza signos vitales del paciente');
INSERT INTO PC_ROL (CODIGO, NOMBRE, DESCRIPCION) VALUES ('ADMIN',   'Administrador', 'Equipo de soporte; gestiona usuarios y configuracion');

-- Permisos
INSERT INTO PC_PERMISO (CODIGO, NOMBRE, DESCRIPCION) VALUES ('VER',      'Ver',      'Solo lectura de datos');
INSERT INTO PC_PERMISO (CODIGO, NOMBRE, DESCRIPCION) VALUES ('EDITAR',   'Editar',   'Lectura y modificacion de datos clinicos/config');
INSERT INTO PC_PERMISO (CODIGO, NOMBRE, DESCRIPCION) VALUES ('COMPLETO', 'Completo', 'Control total, incluida gestion de usuarios');

-- Relacion rol-permiso (RBAC)
INSERT INTO PC_ROL_PERMISO (ID_ROL, ID_PERMISO) SELECT R.ID_ROL, P.ID_PERMISO FROM PC_ROL R, PC_PERMISO P WHERE R.CODIGO='MEDICO'    AND P.CODIGO IN ('VER','EDITAR');
INSERT INTO PC_ROL_PERMISO (ID_ROL, ID_PERMISO) SELECT R.ID_ROL, P.ID_PERMISO FROM PC_ROL R, PC_PERMISO P WHERE R.CODIGO='ENFERMERO' AND P.CODIGO IN ('VER','EDITAR');
INSERT INTO PC_ROL_PERMISO (ID_ROL, ID_PERMISO) SELECT R.ID_ROL, P.ID_PERMISO FROM PC_ROL R, PC_PERMISO P WHERE R.CODIGO='FAMILIAR'  AND P.CODIGO IN ('VER');
INSERT INTO PC_ROL_PERMISO (ID_ROL, ID_PERMISO) SELECT R.ID_ROL, P.ID_PERMISO FROM PC_ROL R, PC_PERMISO P WHERE R.CODIGO='ADMIN'     AND P.CODIGO IN ('VER','EDITAR','COMPLETO');

-- Parentescos
INSERT INTO PC_PARENTESCO (NOMBRE) VALUES ('Hijo/a');
INSERT INTO PC_PARENTESCO (NOMBRE) VALUES ('Conyuge');
INSERT INTO PC_PARENTESCO (NOMBRE) VALUES ('Hermano/a');
INSERT INTO PC_PARENTESCO (NOMBRE) VALUES ('Padre/Madre');
INSERT INTO PC_PARENTESCO (NOMBRE) VALUES ('Otro');

-- Modalidades de atencion
INSERT INTO PC_MODALIDAD_ATENCION (NOMBRE) VALUES ('Domicilio');
INSERT INTO PC_MODALIDAD_ATENCION (NOMBRE) VALUES ('Hospitalizacion domiciliaria');
INSERT INTO PC_MODALIDAD_ATENCION (NOMBRE) VALUES ('Clinica');

-- Estados de paciente
INSERT INTO PC_ESTADO_PACIENTE (CODIGO, NOMBRE) VALUES ('ESTABLE',     'Estable');
INSERT INTO PC_ESTADO_PACIENTE (CODIGO, NOMBRE) VALUES ('OBSERVACION', 'En observacion');
INSERT INTO PC_ESTADO_PACIENTE (CODIGO, NOMBRE) VALUES ('CRITICO',     'Critico');
INSERT INTO PC_ESTADO_PACIENTE (CODIGO, NOMBRE) VALUES ('ALTA',        'Alta');

-- Estados de lectura (semaforo)
INSERT INTO PC_ESTADO_LECTURA (CODIGO, NOMBRE, COLOR) VALUES ('NORMAL',   'Normal',   'verde');
INSERT INTO PC_ESTADO_LECTURA (CODIGO, NOMBRE, COLOR) VALUES ('ATENCION', 'Atencion', 'amarillo');
INSERT INTO PC_ESTADO_LECTURA (CODIGO, NOMBRE, COLOR) VALUES ('CRITICO',  'Critico',  'rojo');

-- Niveles de alerta
INSERT INTO PC_NIVEL_ALERTA (CODIGO, NOMBRE) VALUES ('AMARILLO', 'Atencion (amarillo)');
INSERT INTO PC_NIVEL_ALERTA (CODIGO, NOMBRE) VALUES ('ROJO',     'Critico (rojo)');

-- Estados de alerta
INSERT INTO PC_ESTADO_ALERTA (CODIGO, NOMBRE) VALUES ('GENERADA',   'Generada');
INSERT INTO PC_ESTADO_ALERTA (CODIGO, NOMBRE) VALUES ('NOTIFICADA', 'Notificada');
INSERT INTO PC_ESTADO_ALERTA (CODIGO, NOMBRE) VALUES ('RECONOCIDA', 'Reconocida');
INSERT INTO PC_ESTADO_ALERTA (CODIGO, NOMBRE) VALUES ('RESUELTA',   'Resuelta');

-- Estados de notificacion
INSERT INTO PC_ESTADO_NOTIFICACION (CODIGO, NOMBRE) VALUES ('PENDIENTE', 'Pendiente');
INSERT INTO PC_ESTADO_NOTIFICACION (CODIGO, NOMBRE) VALUES ('ENVIADO',   'Enviado');
INSERT INTO PC_ESTADO_NOTIFICACION (CODIGO, NOMBRE) VALUES ('ENTREGADO', 'Entregado');
INSERT INTO PC_ESTADO_NOTIFICACION (CODIGO, NOMBRE) VALUES ('FALLIDO',   'Fallido');

-- Catalogo de signos vitales (tipo, unidad, rango normal de referencia, itemid MIMIC)
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('FC',   'Frecuencia cardiaca',     'bpm',  220045, 60, 100, 0);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('SPO2', 'Saturacion de oxigeno',   '%',    220277, 92, 100, 0);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('PAS',  'Presion sistolica',       'mmHg', 220179, 90, 140, 0);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('PAD',  'Presion diastolica',      'mmHg', 220180, 60, 90,  0);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('TEMP', 'Temperatura',             'C',    223762, 35.5, 37.5, 1);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('FR',   'Frecuencia respiratoria', 'rpm',  220210, 12, 20,  0);

-- Los dos parametros que completan la escala NEWS2 (que evalua 7). Van sin
-- ITEMID_MIMIC porque no se copian de una fila: se derivan en el replayer a partir
-- de varias columnas de texto de MIMIC y llegan ya numericos.
--   GCS   : escala de Glasgow, 3 a 15. Solo 15 es "alerta"; por debajo hay deterioro.
--   O2SUP : 0 = respira aire ambiente, 1 = recibe oxigeno suplementario.
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('GCS',  'Nivel de conciencia',     'pts',  NULL,   15, 15,  0);
INSERT INTO PC_SIGNO_VITAL (CODIGO, NOMBRE, UNIDAD, ITEMID_MIMIC, RANGO_MIN, RANGO_MAX, DECIMALES) VALUES ('O2SUP','Oxigeno suplementario',   's/n',  NULL,   0,  0,   0);

COMMIT;

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT
--------------------------------------------------------------------------------
